---
kind: pipeline
type: docker
name: default

steps:
  - name: yml-lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: build
    image: golang:1.16
    commands:
      - ./build.sh
  - name: publish
    image: plugins/github-release:1
    settings:
      api_key:
        from_secret: github-token
      files:
        - go-openbsd-amd64-bootstrap.tbz
    when:
      event:
        - tag
